version: '3'

services:

  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - 8083:8080

  login-api:
    build: 
      context: ./login-api
    ports:
      - 8082:8080

      
  register-api:
    build: 
      context: ./register-api
    ports:
      - 8081:8080
  
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./api-gateway:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - api-gateway
      - login-api
      - register-api